    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Kapela Zatím Anna</title>
        <base href="/localhost" />
        <title><?= $titulek ?></title>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicova_slova ?>" />
        <link rel="stylesheet" href="/sablona.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Kantumruy+Pro:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>

    <main>

        <div class="logoheader">
            <img src="images/logozatimanna.png">
        </div>


        <nav>
            <ul>
                <li><a class="navlinksa" href="uvod">Úvod</a></li>
                <li><a class="navlinksa" href="obsazeni">Obsazení</a></li>
                <li><a class="navlinksa" href="repertoar">Repertoár</a></li>
                <li><a class="navlinksa" href="kalendarakci">Kalendář akcí</a></li>
                <li><a class="navlinksa" href="fotogalerie">Fotogalerie</a></li>
                <li><a class="navlinksa" href="proporadatele">Pro pořadatele</a></li>
                <li><a class="navlinksa" href="kontakt">Kontakt</a></li>
            </ul>
        </nav>


        <article>
            <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
        </article>

    </main>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </html>