<div class="backroundimage">
<article>
<h1>Kdo jsme?</h1>
<p>Jsme šestičlenná kapela ze středních Čech, která vám hraje již 5 let.
    Zajišťujeme hudební produkci na plesy, svatby, firemní večírky, oslavy, taneční zábavy,
    firemní večírky, městské akce a další akce podobného charakteru.<br>
    <br>
    Náš repertoár je velmi různorodý a postavený na multižánrovosti.
    Rádi vám zahrajeme taneční hudbu, rock, jazz, ale i lidové písně.
    Pro lepší představu se podívejte do záložky "repertoár", kde naleznete menší výběr písní.</p>

    <a class="buttonrezervace" href="kontakt">Zarezervovat</a>
</article>
</div>